### ISSUE TITLE
Protein sequence length limit

### ISSUE THREAD

**Issue by rakeshr10** [mheinzinger/ProstT5#12]
Hi @mheinzinger,

  I was using ProstT5 on some protein sequences. I noticed it was not predicting 3Di sequences for protein sequence length of greater than 1000 residues. What is the reason and rationale for this? 

  Are these limits due to the way the model was trained, if so what are the other limitations?

Regards
Rakesh

**Comment by mheinzinger** [comment]
Which script did you use exactly? If you use [this one](https://github.com/mheinzinger/ProstT5/blob/main/scripts/predict_3Di_encoderOnly.py) which only uses ProstT5-encoder + CNN to predict 3Di, you should get predictions for all proteins up to the point where your GPU runs out of memory (but this should not quit silently but throw an exception, so you should see why it fails).
