### ISSUE TITLE
Readme update: model.full() - AttributeError: 'T5EncoderModel' object has no attribute 'full'

### ISSUE THREAD

**Issue by robsyc** [mheinzinger/ProstT5#35]
For people trying to get the model running locally on CPU, it might be beneficial to update the instructions in `README.md` to:

`model.float() if device.type=='cpu' else model.half()`

Rather than

`model.full() if device=='cpu' else model.half()`

The latter causes an exception

**Comment by mheinzinger** [comment]
Thanks for pointing out. Should be fixed now :)
